baseURL = "http://192.168.1.220:1313/"
languageCode = "en-us"
title = "Personal Blog"
theme = "hugo-bearneo"
enableRobotsTXT = true
paginate = 10

[permalinks]
  posts = "/p/:slug"

[params]
  description = "Notes, essays, and experiments."
  toc = true
  imageZoom = true
  groupByYear = true
  postSearch = true
  followFeedId = ""
  followUserId = ""

[params.author]
  name = "Matheus Candido"
